<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-09 at 16:33:22.
 */
class MessageTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SOSO_Logger_Message
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SOSO_Logger_Message;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SOSO_Logger_Message::getArrayCopy
     * @todo   Implement testGetArrayCopy().
     */
    public function testGetArrayCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
    }

    /**
     * @covers SOSO_Logger_Message::setPairs
     * @todo   Implement testSetPairs().
     */
    public function testSetPairs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
	$this->assertTrue(true);
    }

    /**
     * @covers SOSO_Logger_Message::setMessage
     * @todo   Implement testSetMessage().
     */
    public function testSetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::setContext
     * @todo   Implement testSetContext().
     */
    public function testSetContext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::setLevel
     * @todo   Implement testSetLevel().
     */
    public function testSetLevel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::setCategory
     * @todo   Implement testSetCategory().
     */
    public function testSetCategory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::setDatetime
     * @todo   Implement testSetDatetime().
     */
    public function testSetDatetime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::setExtra
     * @todo   Implement testSetExtra().
     */
    public function testSetExtra()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::setFormatted
     * @todo   Implement testSetFormatted().
     */
    public function testSetFormatted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getDatetimeString
     * @todo   Implement testGetDatetimeString().
     */
    public function testGetDatetimeString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getFormatted
     * @todo   Implement testGetFormatted().
     */
    public function testGetFormatted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getLevel
     * @todo   Implement testGetLevel().
     */
    public function testGetLevel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getContext
     * @todo   Implement testGetContext().
     */
    public function testGetContext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getCategory
     * @todo   Implement testGetCategory().
     */
    public function testGetCategory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getDatetime
     * @todo   Implement testGetDatetime().
     */
    public function testGetDatetime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getExtra
     * @todo   Implement testGetExtra().
     */
    public function testGetExtra()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_Message::getLevelName
     * @todo   Implement testGetLevelName().
     */
    public function testGetLevelName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
