<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-09 at 16:33:22.
 */
class SyslogTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SOSO_Logger_Syslog
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SOSO_Logger_Syslog;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SOSO_Logger_Syslog::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
