<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-09 at 16:13:34.
 */
class LogTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SOSO_Log
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SOSO_Log;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SOSO_Log::getLogging
     * @todo   Implement testGetLogging().
     */
    public function testGetLogging()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::basicConfig
     * @todo   Implement testBasicConfig().
     */
    public function testBasicConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::addLogger
     * @todo   Implement testAddLogger().
     */
    public function testAddLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::popLogger
     * @todo   Implement testPopLogger().
     */
    public function testPopLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::getLogger
     * @todo   Implement testGetLogger().
     */
    public function testGetLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::addProcessor
     * @todo   Implement testAddProcessor().
     */
    public function testAddProcessor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::popProcessor
     * @todo   Implement testPopProcessor().
     */
    public function testPopProcessor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::addMessage
     * @todo   Implement testAddMessage().
     */
    public function testAddMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::getLevelName
     * @todo   Implement testGetLevelName().
     */
    public function testGetLevelName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::addLevelName
     * @todo   Implement testAddLevelName().
     */
    public function testAddLevelName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::alert
     * @todo   Implement testAlert().
     */
    public function testAlert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::debug
     * @todo   Implement testDebug().
     */
    public function testDebug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::info
     * @todo   Implement testInfo().
     */
    public function testInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::notice
     * @todo   Implement testNotice().
     */
    public function testNotice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::warn
     * @todo   Implement testWarn().
     */
    public function testWarn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::err
     * @todo   Implement testErr().
     */
    public function testErr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::crit
     * @todo   Implement testCrit().
     */
    public function testCrit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::fatal
     * @todo   Implement testFatal().
     */
    public function testFatal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Log::emerg
     * @todo   Implement testEmerg().
     */
    public function testEmerg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
