<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-09 at 16:33:21.
 */
class FileRotatingTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SOSO_Logger_FileRotating
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SOSO_Logger_FileRotating;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SOSO_Logger_FileRotating::setFilecount
     * @todo   Implement testSetFilecount().
     */
    public function testSetFilecount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_FileRotating::setFilesize
     * @todo   Implement testSetFilesize().
     */
    public function testSetFilesize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_FileRotating::canRotate
     * @todo   Implement testCanRotate().
     */
    public function testCanRotate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_FileRotating::doRotate
     * @todo   Implement testDoRotate().
     */
    public function testDoRotate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
