<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-09 at 16:33:22.
 */
class LineFormatterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SOSO_Logger_LineFormatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SOSO_Logger_LineFormatter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SOSO_Logger_LineFormatter::setFormat
     * @todo   Implement testSetFormat().
     */
    public function testSetFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_LineFormatter::setDateFormat
     * @todo   Implement testSetDateFormat().
     */
    public function testSetDateFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SOSO_Logger_LineFormatter::format
     * @todo   Implement testFormat().
     */
    public function testFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
